FROM centos:centos8

RUN yum install -y java-1.8.0-openjdk \
    && yum install -y ncurses

ENV JAVA_HOME /etc/alternatives/jre
COPY osmosis.tar.gz /tmp/
RUN mkdir app
RUN tar xf /tmp/osmosis.tar.gz --directory=/app
RUN rm /tmp/osmosis.tar.gz

COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod 755 /usr/local/bin/docker-entrypoint.sh

ENTRYPOINT [ "/usr/local/bin/docker-entrypoint.sh" ]
