FROM node:16.0.0-alpine3.11

RUN apk update && apk add iperf3

COPY performance.tar.gz /tmp/performance.tar.gz
RUN mkdir /app
RUN tar xf /tmp/performance.tar.gz --directory=/app
RUN rm /tmp/performance.tar.gz

RUN npm --prefix ./app/performance install ./app/performance

